/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payoff-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Payoff Plan */
        post: operations["create_payoff_plan_v1_payoff_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/financial-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Financial Report
         * @description Calculate affordability first, then simulate only a feasible plan.
         */
        post: operations["create_financial_report_v1_financial_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CashFlowOut */
        CashFlowOut: {
            /** Total Monthly Income */
            total_monthly_income: string;
            /** Total Monthly Expenses */
            total_monthly_expenses: string;
            /** Total Minimum Debt Payments */
            total_minimum_debt_payments: string;
            /** Available Monthly Cash Flow */
            available_monthly_cash_flow: string;
            /** Shortfall */
            shortfall: string;
            /** Maximum Affordable Extra Payment */
            maximum_affordable_extra_payment: string;
            /**
             * Status
             * @enum {string}
             */
            status: "deficit" | "break_even" | "surplus";
        };
        /**
         * ComparisonOut
         * @description Precomputed strategy differences; null when a plan never pays off.
         */
        ComparisonOut: {
            /** Interest Saved Snowball Vs Baseline */
            interest_saved_snowball_vs_baseline: string | null;
            /** Interest Saved Avalanche Vs Baseline */
            interest_saved_avalanche_vs_baseline: string | null;
            /** Interest Saved Avalanche Vs Snowball */
            interest_saved_avalanche_vs_snowball: string | null;
            /** Months Saved Snowball Vs Baseline */
            months_saved_snowball_vs_baseline: number | null;
            /** Months Saved Avalanche Vs Baseline */
            months_saved_avalanche_vs_baseline: number | null;
            /** Months Saved Avalanche Vs Snowball */
            months_saved_avalanche_vs_snowball: number | null;
        };
        /** DebtIn */
        DebtIn: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Balance */
            balance: string;
            /** Apr */
            apr: string;
            /** Minimum Payment */
            minimum_payment: string;
        };
        /** DebtPaymentBudgetOut */
        DebtPaymentBudgetOut: {
            /** Requested Extra Monthly Payment */
            requested_extra_monthly_payment: string;
            /** Planned Extra Monthly Payment */
            planned_extra_monthly_payment: string;
            /** Unallocated Cash Flow */
            unallocated_cash_flow: string;
            /** Extra Payment Gap */
            extra_payment_gap: string;
            /** Is Affordable */
            is_affordable: boolean;
        };
        /** DebtPayoffOut */
        DebtPayoffOut: {
            /** Debt Id */
            debt_id: string;
            /** Name */
            name: string;
            /** Months To Payoff */
            months_to_payoff: number;
            /** Payoff Month */
            payoff_month: string;
            /** Total Interest Paid */
            total_interest_paid: string;
        };
        /** ExpenseIn */
        ExpenseIn: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Category
             * @enum {string}
             */
            category: "housing" | "food" | "utilities" | "transportation" | "insurance" | "healthcare" | "childcare" | "subscriptions" | "personal" | "other";
            /** Monthly Amount */
            monthly_amount: string;
        };
        /** FinancialReportDebtIn */
        FinancialReportDebtIn: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Balance */
            balance: string;
            /** Apr */
            apr: string;
            /** Minimum Payment */
            minimum_payment: string;
            /**
             * Type
             * @default credit_card
             * @enum {string}
             */
            type: "credit_card" | "auto_loan" | "personal_loan" | "student_loan" | "medical_debt" | "other";
        };
        /** FinancialReportRequest */
        FinancialReportRequest: {
            /** Incomes */
            incomes: components["schemas"]["IncomeIn"][];
            /** Expenses */
            expenses: components["schemas"]["ExpenseIn"][];
            /** Debts */
            debts: components["schemas"]["FinancialReportDebtIn"][];
            /** Requested Extra Monthly Payment */
            requested_extra_monthly_payment: string;
            /** Start Month */
            start_month: string;
        };
        /** FinancialReportResponse */
        FinancialReportResponse: {
            /** Start Month */
            start_month: string;
            /** Total Debt */
            total_debt: string;
            cash_flow: components["schemas"]["CashFlowOut"];
            debt_payment_budget: components["schemas"]["DebtPaymentBudgetOut"];
            payoff_plan: components["schemas"]["PayoffPlanResponse"] | null;
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationOut"][];
            /** Estimate Disclosure */
            estimate_disclosure: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncomeIn */
        IncomeIn: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Monthly Amount */
            monthly_amount: string;
        };
        /** MonthlyTotalOut */
        MonthlyTotalOut: {
            /** Month Number */
            month_number: number;
            /** Month */
            month: string;
            /** Remaining Balance */
            remaining_balance: string;
            /** Cumulative Interest */
            cumulative_interest: string;
        };
        /** PayoffPlanRequest */
        PayoffPlanRequest: {
            /** Debts */
            debts: components["schemas"]["DebtIn"][];
            /** Extra Monthly Payment */
            extra_monthly_payment: string;
            /** Start Month */
            start_month: string;
        };
        /** PayoffPlanResponse */
        PayoffPlanResponse: {
            /** Start Month */
            start_month: string;
            scenarios: components["schemas"]["ScenariosOut"];
            comparison: components["schemas"]["ComparisonOut"];
        };
        /** RecommendationOut */
        RecommendationOut: {
            /**
             * Code
             * @enum {string}
             */
            code: "close_shortfall" | "protect_minimums" | "reduce_extra_payment" | "compare_strategies" | "assign_remaining_surplus" | "build_cash_reserve";
            /** Title */
            title: string;
            /** Detail */
            detail: string;
        };
        /** ScenarioOut */
        ScenarioOut: {
            /**
             * Strategy
             * @enum {string}
             */
            strategy: "snowball" | "avalanche" | "minimum_only";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "paid_off" | "never_pays_off";
            /** Months To Payoff */
            months_to_payoff: number | null;
            /** Payoff Month */
            payoff_month: string | null;
            /** Underwater Debt Ids */
            underwater_debt_ids: string[];
            /** Total Interest Paid */
            total_interest_paid: string;
            /** Total Paid */
            total_paid: string;
            /** Debt Payoffs */
            debt_payoffs: components["schemas"]["DebtPayoffOut"][];
            /** Monthly Totals */
            monthly_totals: components["schemas"]["MonthlyTotalOut"][];
        };
        /** ScenariosOut */
        ScenariosOut: {
            snowball: components["schemas"]["ScenarioOut"];
            avalanche: components["schemas"]["ScenarioOut"];
            baseline: components["schemas"]["ScenarioOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_payoff_plan_v1_payoff_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayoffPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoffPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_financial_report_v1_financial_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinancialReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
