// Generated by `npm run gen:api` from the backend's /openapi.json.
// Do not edit by hand. Regenerate after any change to backend/app/api/schemas.py.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payoff-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Payoff Plan */
        post: operations["create_payoff_plan_v1_payoff_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/payoff-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Payoff Plan
         * @description The signed-in user's plan, computed from their stored debts.
         *
         *     Money arrives as a query parameter here, so it is a string by definition:
         *     the Money type still parses it to Decimal, but its reject-bare-numbers
         *     guarantee is trivially satisfied. The bounds are what do the work.
         */
        get: operations["my_payoff_plan_v1_me_payoff_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/debts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Debts */
        get: operations["list_debts_v1_debts_get"];
        put?: never;
        /** Create Debt */
        post: operations["create_debt_v1_debts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/debts/{debt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Debt */
        delete: operations["delete_debt_v1_debts__debt_id__delete"];
        options?: never;
        head?: never;
        /** Update Debt */
        patch: operations["update_debt_v1_debts__debt_id__patch"];
        trace?: never;
    };
    "/v1/payoff-plans/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Payoff Plan */
        post: operations["explain_payoff_plan_v1_payoff_plans_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ComparisonOut
         * @description Every delta the AI layer is permitted to state.
         *
         *     Nullable throughout, because you cannot subtract from a plan that never
         *     pays off. A delta omitted here is a delta the model would compute in
         *     prose, which is the exact failure the engine/AI split exists to prevent.
         */
        ComparisonOut: {
            /** Interest Saved Snowball Vs Baseline */
            interest_saved_snowball_vs_baseline: string | null;
            /** Interest Saved Avalanche Vs Baseline */
            interest_saved_avalanche_vs_baseline: string | null;
            /** Interest Saved Avalanche Vs Snowball */
            interest_saved_avalanche_vs_snowball: string | null;
            /** Months Saved Snowball Vs Baseline */
            months_saved_snowball_vs_baseline: number | null;
            /** Months Saved Avalanche Vs Baseline */
            months_saved_avalanche_vs_baseline: number | null;
            /** Months Saved Avalanche Vs Snowball */
            months_saved_avalanche_vs_snowball: number | null;
        };
        /**
         * DebtCreate
         * @description A new debt.
         *
         *     No `id` -- the database generates it -- and no `user_id`, which comes from
         *     the verified token and never from the body. Accepting `user_id` from a
         *     request body is how a caller writes into someone else's account.
         */
        DebtCreate: {
            /** Name */
            name: string;
            /**
             * Type
             * @default credit_card
             */
            type: string;
            /** Balance */
            balance: string;
            /** Apr */
            apr: string;
            /** Minimum Payment */
            minimum_payment: string;
        };
        /** DebtIn */
        DebtIn: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Balance */
            balance: string;
            /** Apr */
            apr: string;
            /** Minimum Payment */
            minimum_payment: string;
        };
        /** DebtMonthOut */
        DebtMonthOut: {
            /** Debt Id */
            debt_id: string;
            /** Starting Balance */
            starting_balance: string;
            /** Interest Charged */
            interest_charged: string;
            /** Payment Applied */
            payment_applied: string;
            /** Ending Balance */
            ending_balance: string;
        };
        /**
         * DebtOut
         * @description A stored debt on the wire.
         *
         *     `id` is a UUID rather than a str: the database returns a UUID object and
         *     Pydantic does not coerce it to str, so typing it correctly here is what
         *     lets a row map straight onto this model. It still serializes to a JSON
         *     string, so the wire contract is unchanged.
         */
        DebtOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Balance */
            balance: string;
            /** Apr */
            apr: string;
            /** Minimum Payment */
            minimum_payment: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DebtPayoffOut */
        DebtPayoffOut: {
            /** Debt Id */
            debt_id: string;
            /** Name */
            name: string;
            /** Months To Payoff */
            months_to_payoff: number;
            /** Payoff Month */
            payoff_month: string;
            /** Total Interest Paid */
            total_interest_paid: string;
        };
        /**
         * DebtUpdate
         * @description A partial update. Every field optional, but not all of them at once.
         */
        DebtUpdate: {
            /** Name */
            name?: string | null;
            /** Type */
            type?: string | null;
            /** Balance */
            balance?: string | null;
            /** Apr */
            apr?: string | null;
            /** Minimum Payment */
            minimum_payment?: string | null;
        };
        /**
         * ExplainResponse
         * @description A narrative of a payoff comparison.
         *
         *     `source` reports which provider served it. A client that cannot tell
         *     whether it received generated prose or the deterministic fallback cannot
         *     decide whether to label it, and silently degrading should be visible.
         */
        ExplainResponse: {
            /** Headline */
            headline: string;
            /** Body */
            body: string;
            /**
             * Source
             * @enum {string}
             */
            source: "model" | "template";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MonthOut */
        MonthOut: {
            /** Month Number */
            month_number: number;
            /** Month */
            month: string;
            /** Debts */
            debts: components["schemas"]["DebtMonthOut"][];
            /** Total Payment */
            total_payment: string;
            /** Total Interest */
            total_interest: string;
            /** Remaining Balance */
            remaining_balance: string;
        };
        /** MonthlyTotalOut */
        MonthlyTotalOut: {
            /** Month Number */
            month_number: number;
            /** Month */
            month: string;
            /** Remaining Balance */
            remaining_balance: string;
            /** Cumulative Interest */
            cumulative_interest: string;
        };
        /** PayoffPlanRequest */
        PayoffPlanRequest: {
            /** Debts */
            debts: components["schemas"]["DebtIn"][];
            /** Extra Monthly Payment */
            extra_monthly_payment: string;
            /** Start Month */
            start_month: string;
        };
        /** PayoffPlanResponse */
        PayoffPlanResponse: {
            /** Start Month */
            start_month: string;
            scenarios: components["schemas"]["ScenariosOut"];
            comparison: components["schemas"]["ComparisonOut"];
        };
        /** ScenarioOut */
        ScenarioOut: {
            /**
             * Strategy
             * @enum {string}
             */
            strategy: "snowball" | "avalanche" | "minimum_only";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "paid_off" | "never_pays_off";
            /** Months To Payoff */
            months_to_payoff: number | null;
            /** Payoff Month */
            payoff_month: string | null;
            /** Underwater Debt Ids */
            underwater_debt_ids: string[];
            /** Total Interest Paid */
            total_interest_paid: string;
            /** Total Paid */
            total_paid: string;
            /** Debt Payoffs */
            debt_payoffs: components["schemas"]["DebtPayoffOut"][];
            /** Monthly Totals */
            monthly_totals: components["schemas"]["MonthlyTotalOut"][];
            /** Schedule */
            schedule: components["schemas"]["MonthOut"][] | null;
            /** Schedule Truncated */
            schedule_truncated: boolean;
        };
        /** ScenariosOut */
        ScenariosOut: {
            snowball: components["schemas"]["ScenarioOut"];
            avalanche: components["schemas"]["ScenarioOut"];
            baseline: components["schemas"]["ScenarioOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_payoff_plan_v1_payoff_plans_post: {
        parameters: {
            query?: {
                /** @description Pass 'full' to include the per-debt month-by-month schedule. */
                detail?: "full" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayoffPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoffPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_payoff_plan_v1_me_payoff_plan_get: {
        parameters: {
            query: {
                extra_monthly_payment: number | string;
                start_month: string;
                /** @description Pass 'full' to include the per-debt month-by-month schedule. */
                detail?: "full" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoffPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_debts_v1_debts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtOut"][];
                };
            };
        };
    };
    create_debt_v1_debts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebtCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_debt_v1_debts__debt_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_debt_v1_debts__debt_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                debt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebtUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_payoff_plan_v1_payoff_plans_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayoffPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
